"""Config builder + local router process management for /switchyard.

Generates a Switchyard routes YAML from key=value overrides on top of
NVIDIA-friendly defaults (strong = Opus 4.8 via anthropic format, weak =
Nemotron Ultra, Nano classifier), and starts/stops a local router with it.
Everything lives under ~/.hermes/switchyard/ (user-owned — plugin updates
never touch it). API keys are referenced as ${ENV_VAR} in the YAML and are
never written to disk.
"""
from __future__ import annotations

import json
import os
import shutil
import signal
import subprocess
import time
from pathlib import Path

SW_DIR = Path(os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))) / "switchyard"
CONFIG_PATH = SW_DIR / "routes.yaml"
STATE_PATH = SW_DIR / "router-state.json"
LOG_PATH = SW_DIR / "router.log"

DEFAULTS = {
    "strong": "aws/anthropic/bedrock-claude-opus-4-8",
    "strong_format": "anthropic",
    "weak": "nvidia/nvidia/nemotron-3-ultra",
    "weak_format": "openai",
    "classifier": "nvidia/nvidia/Nemotron-3-Nano-30B-A3B",
    "base_url": "https://inference-api.nvidia.com/v1",
    "key_env": "NVIDIA_API_KEY",
    "port": "4100",
    "profile": "coding_agent",
    "min_confidence": "0.6",
    "timeout_secs": "600",
}
KNOWN_KEYS = set(DEFAULTS)


def parse_kv(raw_args):
    """'strong=x weak=y port=4200' -> (opts dict, unknown keys list)."""
    opts, unknown = dict(DEFAULTS), []
    for tok in (raw_args or "").split():
        if "=" not in tok:
            unknown.append(tok)
            continue
        k, v = tok.split("=", 1)
        k, v = k.strip().lower(), v.strip()
        if k in KNOWN_KEYS and v:
            opts[k] = v
        else:
            unknown.append(tok)
    return opts, unknown


def _short(model):
    return str(model).rsplit("/", 1)[-1]


def build_yaml(opts):
    key = "${%s}" % opts["key_env"]
    o = dict(opts)
    o["key"] = key
    return """# Switchyard routes — generated by /switchyard init (edit freely)
# strong = {strong}   weak = {weak}
# API key comes from the {key_env} environment variable at router start.

defaults:
  api_key: {key}
  base_url: {base_url}
  format: openai

routes:
  switchyard:                        # the one model users pick — classifier
    type: deterministic              # routes each request to a tier behind it
    profile: {profile}
    enable_stats: true
    fallback_target_on_evict: strong
    classifier:
      model: {classifier}
      api_key: {key}
      base_url: {base_url}
      timeout_secs: 120
      min_confidence: {min_confidence}
      fail_open: true
      recent_turn_window: 4
    strong:
      id: strong
      model: {strong}
      api_key: {key}
      base_url: {base_url}
      format: {strong_format}
      timeout_secs: {timeout_secs}
    weak:
      id: weak
      model: {weak}
      api_key: {key}
      base_url: {base_url}
      format: {weak_format}
      timeout_secs: {timeout_secs}

# Pinning to one model needs no extra routes: every upstream catalog model is
# also exposed as a passthrough route (e.g. /model {strong}).
""".format(**o)


def write_config(opts, path=None):
    path = Path(path) if path else CONFIG_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_yaml(opts))
    return path


# ---------------------------------------------------------------------------
# provider entry in config.yaml (/switchyard connect|disconnect)
# ---------------------------------------------------------------------------

HERMES_CONFIG = Path(os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))) / "config.yaml"
_MARK_BEGIN = "  # >>> switchyard provider — managed by /switchyard connect >>>"
_MARK_END = "  # <<< switchyard provider — remove with /switchyard disconnect <<<"


def _provider_block(url, route_ids):
    models = "[" + ", ".join(route_ids) + "]" if route_ids else "[]"
    return "\n".join([
        _MARK_BEGIN,
        "  switchyard:",
        "    name: Switchyard",
        f"    base_url: {url}",
        "    key_env: SWITCHYARD_API_KEY",
        f"    models: {models}",
        _MARK_END,
    ])


def connect_provider(url, route_ids, config_path=None):
    """Add a `switchyard` entry under `providers:` in config.yaml.

    Marker-bounded and comment-preserving: only the managed block is ever
    touched. Re-running replaces the managed block (url/routes refresh).
    Returns (ok, message).
    """
    path = Path(config_path) if config_path else HERMES_CONFIG
    if not path.exists():
        return False, f"hermes config not found at {path}"
    text = path.read_text()
    block = _provider_block(url, route_ids)

    if _MARK_BEGIN in text and _MARK_END in text:
        head, _, rest = text.partition(_MARK_BEGIN)
        _, _, tail = rest.partition(_MARK_END)
        text = head + block + tail
        path.write_text(text)
        return True, "updated existing switchyard provider entry"

    lines = text.splitlines()
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped in ("providers: {}", "providers: {}  # none"):
            lines[i] = "providers:\n" + block
            path.write_text("\n".join(lines) + ("\n" if text.endswith("\n") else ""))
            return True, "added switchyard provider (replaced empty providers: {})"
        if stripped == "providers:":
            lines[i] = line + "\n" + block
            path.write_text("\n".join(lines) + ("\n" if text.endswith("\n") else ""))
            return True, "added switchyard provider under existing providers: key"
    path.write_text(text.rstrip("\n") + "\n\nproviders:\n" + block + "\n")
    return True, "added providers: section with switchyard entry"


def disconnect_provider(config_path=None):
    """Remove the managed provider block. Returns (ok, message)."""
    path = Path(config_path) if config_path else HERMES_CONFIG
    if not path.exists():
        return False, f"hermes config not found at {path}"
    text = path.read_text()
    if _MARK_BEGIN not in text or _MARK_END not in text:
        return False, "no managed switchyard provider entry found"
    head, _, rest = text.partition(_MARK_BEGIN)
    _, _, tail = rest.partition(_MARK_END)
    lines = (head + tail.lstrip("\n")).splitlines()
    # collapse a now-childless `providers:` key back to `providers: {}`
    for i, line in enumerate(lines):
        if line.strip() == "providers:":
            nxt = next((x for x in lines[i + 1:] if x.strip()), "")
            if not nxt.startswith(" "):
                lines[i] = "providers: {}"
            break
    path.write_text("\n".join(lines) + "\n")
    return True, "switchyard provider entry removed"


# ---------------------------------------------------------------------------
# router process management
# ---------------------------------------------------------------------------

def find_switchyard_bin(settings=None):
    """settings['switchyard_bin'] > $SWITCHYARD_BIN > PATH lookup.

    With settings=None, falls back to the plugin's own settings.json (so the
    shell CLI honors a bin saved via /switchyard bin).
    """
    if settings is None:
        try:
            settings = json.loads((Path(__file__).resolve().parent / "settings.json").read_text())
        except Exception:
            settings = {}
    for cand in (
        (settings or {}).get("switchyard_bin"),
        os.environ.get("SWITCHYARD_BIN"),
        shutil.which("switchyard"),
    ):
        if cand and Path(cand).exists():
            return str(cand)
    return None


def _read_state():
    try:
        return json.loads(STATE_PATH.read_text())
    except Exception:
        return None


def _write_state(state):
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2))


def _pid_alive(pid):
    try:
        os.kill(int(pid), 0)
        return True
    except Exception:
        return False


def router_state():
    """{'pid', 'port', 'config', 'running': bool} or None if never started."""
    state = _read_state()
    if not state:
        return None
    state["running"] = _pid_alive(state.get("pid", -1))
    return state


def _key_from_hermes_env_file(key_env):
    """Read KEY=value from $HERMES_HOME/.env (hermes's own env file).

    Agent terminal sessions run with a scrubbed environment, so the exported
    var may be invisible here even when the user has it set. The .env file is
    the sanctioned durable location; we only read it, never write it.
    """
    env_file = Path(os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))) / ".env"
    try:
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            if k.strip().removeprefix("export ").strip() == key_env:
                return v.strip().strip("\"'") or None
    except Exception:
        pass
    return None


def start_router(bin_path, config_path, port, key_env):
    """Spawn `switchyard --routing-profiles <cfg> -- serve` detached.

    Returns (ok, message). The key env var must be set in this environment or
    present in $HERMES_HOME/.env (agent shells are env-scrubbed); it is passed
    to the router process only, never written anywhere.
    """
    state = router_state()
    if state and state.get("running"):
        return False, f"router already running (pid {state['pid']}, port {state['port']}) — /switchyard stop first"
    child_env = dict(os.environ)
    if key_env and not child_env.get(key_env):
        from_file = _key_from_hermes_env_file(key_env)
        if from_file:
            child_env[key_env] = from_file
        else:
            return False, (f"{key_env} is not set here and not in $HERMES_HOME/.env — "
                           f"add `{key_env}=<value>` to ~/.hermes/.env (chmod 600) or export it, then retry")
    SW_DIR.mkdir(parents=True, exist_ok=True)
    log = open(LOG_PATH, "a")
    try:
        proc = subprocess.Popen(
            [bin_path, "--routing-profiles", str(config_path), "--",
             "serve", "--host", "127.0.0.1", "--port", str(port)],
            stdout=log, stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL, start_new_session=True, env=child_env,
        )
    except Exception as exc:
        return False, f"failed to start router: {exc}"
    _write_state({"pid": proc.pid, "port": int(port), "config": str(config_path),
                  "started_at": time.time()})
    return True, (f"router starting (pid {proc.pid}) on http://127.0.0.1:{port} — "
                  f"takes ~15s to bind (upstream catalog fetch); log: {LOG_PATH}")


def stop_router():
    state = router_state()
    if not state:
        return False, "no managed router recorded (only routers started via /switchyard start are managed)"
    if not state.get("running"):
        return False, f"managed router (pid {state.get('pid')}) is not running"
    try:
        os.kill(int(state["pid"]), signal.SIGTERM)
    except Exception as exc:
        return False, f"failed to stop pid {state.get('pid')}: {exc}"
    for _ in range(20):
        if not _pid_alive(state["pid"]):
            break
        time.sleep(0.1)
    alive = _pid_alive(state["pid"])
    return (not alive), ("router stopped" if not alive else f"SIGTERM sent to pid {state['pid']} (still shutting down)")


# ---------------------------------------------------------------------------
# CLI — lets agents (and humans) drive setup from the shell:
#   python3 sw_config.py init [key=value ...]
#   python3 sw_config.py start [bin=PATH] [config=PATH] [port=N]
#   python3 sw_config.py stop | status | connect [URL] | disconnect
# Mirrors the /switchyard slash commands 1:1.
# ---------------------------------------------------------------------------

def _cli(argv):
    import sys as _sys
    _sys.path.insert(0, str(Path(__file__).resolve().parent))
    cmd = argv[0] if argv else "help"
    rest = argv[1:]

    if cmd == "init":
        opts, unknown = parse_kv(" ".join(rest))
        if unknown:
            return 1, "unrecognized: " + " ".join(unknown) + "\nknown keys: " + " ".join(sorted(KNOWN_KEYS))
        path = write_config(opts)
        return 0, (f"wrote {path}\nroute: switchyard — classifier {opts['classifier']} picks between "
                   f"strong ({opts['strong']}) and weak ({opts['weak']})\n"
                   f"api key: read from ${opts['key_env']} at router start")

    if cmd == "start":
        kv = dict(tok.split("=", 1) for tok in rest if "=" in tok)
        bin_path = kv.get("bin") or find_switchyard_bin()
        if not bin_path:
            return 1, "switchyard executable not found — pass bin=PATH or export SWITCHYARD_BIN"
        cfg = Path(kv.get("config") or CONFIG_PATH)
        if not cfg.exists():
            return 1, f"no config at {cfg} — run: python3 sw_config.py init"
        key_env = DEFAULTS["key_env"]
        try:
            import re as _re
            m = _re.search(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", cfg.read_text())
            if m:
                key_env = m.group(1)
        except Exception:
            pass
        ok, msg = start_router(bin_path, cfg, kv.get("port") or DEFAULTS["port"], key_env)
        return (0 if ok else 1), msg

    if cmd == "stop":
        ok, msg = stop_router()
        return (0 if ok else 1), msg

    if cmd == "status":
        state = router_state()
        payload = {"managed_router": state, "config": str(CONFIG_PATH),
                   "config_exists": CONFIG_PATH.exists(),
                   "switchyard_bin": find_switchyard_bin()}
        return 0, json.dumps(payload, indent=2)

    if cmd == "connect":
        import switchyard_client as swc
        url = rest[0] if rest else None
        if not url:
            state = router_state()
            if state and state.get("running"):
                url = f"http://127.0.0.1:{state['port']}/v1"
        if not url:
            return 1, "no url given and no managed router running — connect URL"
        root = swc.detect(url, timeout=2.0)
        if root is None:
            return 1, f"{url} does not fingerprint as a switchyard router (still booting? ~15s)"
        rts, _default = swc.routes(root)
        ok, msg = connect_provider(root + "/v1", [rt["id"] for rt in rts])
        return (0 if ok else 1), msg + f"\nprovider switchyard → {root}/v1 (routes: " + ", ".join(rt["id"] for rt in rts) + ")"

    if cmd == "disconnect":
        ok, msg = disconnect_provider()
        return (0 if ok else 1), msg

    return 1, ("usage: sw_config.py init [k=v ...] | start [bin= config= port=] | stop | "
               "status | connect [URL] | disconnect")


if __name__ == "__main__":
    import sys as _sys
    _code, _msg = _cli(_sys.argv[1:])
    print(_msg)
    _sys.exit(_code)
