"""Config builder + local router process management for /switchyard.

Generates a Switchyard routes YAML from key=value overrides on top of
NVIDIA-friendly defaults (strong = Opus 4.8 via anthropic format, weak =
Nemotron Ultra, Nano classifier), and starts/stops a local router with it.
Everything lives under ~/.hermes/switchyard/ (user-owned — plugin updates
never touch it). API keys are referenced as ${ENV_VAR} in the YAML and are
never written to disk.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import signal
import subprocess
import time
from pathlib import Path

SW_DIR = Path(os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))) / "switchyard"
CONFIG_PATH = SW_DIR / "routes.yaml"
STATE_PATH = SW_DIR / "router-state.json"
LOG_PATH = SW_DIR / "router.log"

DEFAULTS = {
    "strong": "aws/anthropic/bedrock-claude-opus-4-8",
    "strong_format": "anthropic",
    "weak": "nvidia/nvidia/nemotron-3-ultra",
    "weak_format": "openai",
    "classifier": "nvidia/nvidia/Nemotron-3-Nano-30B-A3B",
    "base_url": "https://inference-api.nvidia.com/v1",
    "key_env": "NVIDIA_API_KEY",
    "port": "4100",
    "profile": "coding_agent",
    "min_confidence": "0.6",
    "timeout_secs": "600",
    # Per-tier endpoint overrides (empty = inherit the globals above). Set by
    # /switchyard build when tiers come from different connected providers.
    "strong_base_url": "",
    "strong_key_env": "",
    "weak_base_url": "",
    "weak_key_env": "",
    "classifier_base_url": "",
    "classifier_key_env": "",
    "classifier_format": "openai",
}
KNOWN_KEYS = set(DEFAULTS)


def parse_kv(raw_args):
    """'strong=x weak=y port=4200' -> (opts dict, unknown keys list)."""
    opts, unknown = dict(DEFAULTS), []
    for tok in (raw_args or "").split():
        if "=" not in tok:
            unknown.append(tok)
            continue
        k, v = tok.split("=", 1)
        k, v = k.strip().lower(), v.strip()
        if k in KNOWN_KEYS and v:
            opts[k] = v
        else:
            unknown.append(tok)
    return opts, unknown


def _short(model):
    return str(model).rsplit("/", 1)[-1]


def _tier_block(opts, tier, indent, extra=()):
    """YAML lines for one tier target, honoring per-tier endpoint overrides."""
    pad = " " * indent
    base_url = opts.get(f"{tier}_base_url") or opts["base_url"]
    key_env = opts.get(f"{tier}_key_env") or opts["key_env"]
    lines = [
        f"{pad}model: {opts[tier]}",
        f"{pad}api_key: ${{{key_env}}}",
        f"{pad}base_url: {base_url}",
    ]
    lines.extend(f"{pad}{line}" for line in extra)
    return "\n".join(lines)


def build_yaml(opts):
    strong = _tier_block(opts, "strong", 6, (
        f"format: {opts['strong_format']}",
        f"timeout_secs: {opts['timeout_secs']}",
    ))
    weak = _tier_block(opts, "weak", 6, (
        f"format: {opts['weak_format']}",
        f"timeout_secs: {opts['timeout_secs']}",
    ))
    classifier = _tier_block(opts, "classifier", 6, (
        "timeout_secs: 120",
        f"min_confidence: {opts['min_confidence']}",
        "fail_open: true",
        "recent_turn_window: 4",
    ))
    return f"""# Switchyard routes — generated by /switchyard init|build (edit freely)
# strong = {opts['strong']}   weak = {opts['weak']}
# API keys come from environment variables at router start; none are stored.

defaults:
  api_key: ${{{opts['key_env']}}}
  base_url: {opts['base_url']}
  format: openai

routes:
  switchyard:                        # the one model users pick — classifier
    type: deterministic              # routes each request to a tier behind it
    profile: {opts['profile']}
    enable_stats: true
    fallback_target_on_evict: strong
    classifier:
{classifier}
    strong:
      id: strong
{strong}
    weak:
      id: weak
{weak}

# Pinning to one model needs no extra routes: every upstream catalog model is
# also exposed as a passthrough route (e.g. /model {opts['strong']}).
"""


def write_config(opts, path=None):
    path = Path(path) if path else CONFIG_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_yaml(opts))
    _save_last_opts(opts)
    return path


def _settings_path():
    return Path(__file__).resolve().parent / "settings.json"


def _save_last_opts(opts):
    """Remember the last build (model ids, endpoints, env NAMES — no secrets)
    so the interactive panel can edit one tier without re-asking everything."""
    try:
        data = json.loads(_settings_path().read_text())
        if not isinstance(data, dict):
            data = {}
    except Exception:
        data = {}
    data["last_opts"] = {k: v for k, v in opts.items() if k in KNOWN_KEYS}
    try:
        _settings_path().write_text(json.dumps(data, indent=2))
    except Exception:
        pass


def load_last_opts():
    """Last written config opts, over defaults."""
    opts = dict(DEFAULTS)
    try:
        data = json.loads(_settings_path().read_text())
        saved = data.get("last_opts") or {}
        opts.update({k: v for k, v in saved.items() if k in KNOWN_KEYS})
    except Exception:
        pass
    return opts


# ---------------------------------------------------------------------------
# upstream key preflight
# ---------------------------------------------------------------------------

_TIER_RE = re.compile(
    r"model:\s*(\S+)\s*\n\s*api_key:\s*\$\{([A-Za-z_][A-Za-z0-9_]*)\}"
    r"\s*\n\s*base_url:\s*(\S+)(?:\s*\n\s*format:\s*(\S+))?")


def preflight(config_path=None):
    """Probe every (model, base_url, key_env) tier via a 1-token completion.

    Returns a list of dicts {model, base_url, key_env, status}: HTTP code
    (200 ok, 401/403 key rejected, 4xx model unavailable), "missing" when the
    env var has no value anywhere, or "unreachable". Keys come from the
    environment or $HERMES_HOME/.env and are sent only to their endpoint.
    """
    import sys as _sys
    _sys.path.insert(0, str(Path(__file__).resolve().parent))
    import switchyard_client as swc

    path = Path(config_path) if config_path else CONFIG_PATH
    try:
        text = path.read_text()
    except Exception:
        return []
    tiers = sorted({(m.group(1), m.group(3), m.group(2), m.group(4) or "openai")
                    for m in _TIER_RE.finditer(text)})
    results = []
    for model, base_url, key_env, fmt in tiers:
        value = os.environ.get(key_env) or _key_from_hermes_env_file(key_env)
        if not value:
            status = "missing"
        else:
            code = swc.probe_upstream(base_url, value, model, fmt)
            status = code if code is not None else "unreachable"
        results.append({"model": model, "base_url": base_url,
                        "key_env": key_env, "status": status})
    return results


def preflight_report(results):
    """PASS/FAIL lines for preflight() output; returns (all_ok, text)."""
    if not results:
        return True, "no upstream targets found in config"
    lines, ok = [], True
    for r in results:
        where = f"{r['model']} @ {r['base_url']}"
        if r["status"] == 200:
            lines.append(f"PASS  {where} (${r['key_env']})")
        elif r["status"] in (401, 403):
            ok = False
            lines.append(f"FAIL  ${r['key_env']} rejected by {r['base_url']} for {r['model']} "
                         f"(HTTP {r['status']}) — this endpoint may need a different key type")
        elif r["status"] == "missing":
            ok = False
            lines.append(f"FAIL  ${r['key_env']} has no value (env or ~/.hermes/.env)")
        elif isinstance(r["status"], int):
            ok = False
            lines.append(f"FAIL  {where}: HTTP {r['status']} — key accepted but model unavailable")
        else:
            lines.append(f"WARN  {where} not reachable for preflight")
    return ok, "\n".join(lines)


# ---------------------------------------------------------------------------
# provider entry in config.yaml (/switchyard connect|disconnect)
# ---------------------------------------------------------------------------

HERMES_CONFIG = Path(os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))) / "config.yaml"
_MARK_BEGIN = "  # >>> switchyard provider — managed by /switchyard connect >>>"
_MARK_END = "  # <<< switchyard provider — remove with /switchyard disconnect <<<"


def _provider_block(url, route_ids):
    models = "[" + ", ".join(route_ids) + "]" if route_ids else "[]"
    return "\n".join([
        _MARK_BEGIN,
        "  switchyard:",
        "    name: Switchyard",
        f"    base_url: {url}",
        "    key_env: SWITCHYARD_API_KEY",
        f"    models: {models}",
        _MARK_END,
    ])


def connect_provider(url, route_ids, config_path=None):
    """Add a `switchyard` entry under `providers:` in config.yaml.

    Marker-bounded and comment-preserving: only the managed block is ever
    touched. Re-running replaces the managed block (url/routes refresh).
    Returns (ok, message).
    """
    path = Path(config_path) if config_path else HERMES_CONFIG
    if not path.exists():
        return False, f"hermes config not found at {path}"
    text = path.read_text()
    block = _provider_block(url, route_ids)

    if _MARK_BEGIN in text and _MARK_END in text:
        head, _, rest = text.partition(_MARK_BEGIN)
        _, _, tail = rest.partition(_MARK_END)
        text = head + block + tail
        path.write_text(text)
        return True, "updated existing switchyard provider entry"

    lines = text.splitlines()
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped in ("providers: {}", "providers: {}  # none"):
            lines[i] = "providers:\n" + block
            path.write_text("\n".join(lines) + ("\n" if text.endswith("\n") else ""))
            return True, "added switchyard provider (replaced empty providers: {})"
        if stripped == "providers:":
            lines[i] = line + "\n" + block
            path.write_text("\n".join(lines) + ("\n" if text.endswith("\n") else ""))
            return True, "added switchyard provider under existing providers: key"
    path.write_text(text.rstrip("\n") + "\n\nproviders:\n" + block + "\n")
    return True, "added providers: section with switchyard entry"


def disconnect_provider(config_path=None):
    """Remove the managed provider block. Returns (ok, message)."""
    path = Path(config_path) if config_path else HERMES_CONFIG
    if not path.exists():
        return False, f"hermes config not found at {path}"
    text = path.read_text()
    if _MARK_BEGIN not in text or _MARK_END not in text:
        return False, "no managed switchyard provider entry found"
    head, _, rest = text.partition(_MARK_BEGIN)
    _, _, tail = rest.partition(_MARK_END)
    lines = (head + tail.lstrip("\n")).splitlines()
    # collapse a now-childless `providers:` key back to `providers: {}`
    for i, line in enumerate(lines):
        if line.strip() == "providers:":
            nxt = next((x for x in lines[i + 1:] if x.strip()), "")
            if not nxt.startswith(" "):
                lines[i] = "providers: {}"
            break
    path.write_text("\n".join(lines) + "\n")
    return True, "switchyard provider entry removed"


# ---------------------------------------------------------------------------
# router process management
# ---------------------------------------------------------------------------

def find_switchyard_bin(settings=None):
    """settings['switchyard_bin'] > $SWITCHYARD_BIN > PATH lookup.

    With settings=None, falls back to the plugin's own settings.json (so the
    shell CLI honors a bin saved via /switchyard bin).
    """
    if settings is None:
        try:
            settings = json.loads((Path(__file__).resolve().parent / "settings.json").read_text())
        except Exception:
            settings = {}
    for cand in (
        (settings or {}).get("switchyard_bin"),
        os.environ.get("SWITCHYARD_BIN"),
        shutil.which("switchyard"),
    ):
        if cand and Path(cand).exists():
            return str(cand)
    return None


def _read_state():
    try:
        return json.loads(STATE_PATH.read_text())
    except Exception:
        return None


def _write_state(state):
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2))


def _pid_alive(pid):
    """True when *pid* is a live process. Zombies count as dead — a router
    started from inside a long-lived Hermes session is never reaped by it,
    so kill(0) alone would report the corpse as running forever."""
    try:
        os.kill(int(pid), 0)
    except Exception:
        return False
    try:
        out = subprocess.run(["ps", "-p", str(pid), "-o", "stat="],
                             capture_output=True, text=True, timeout=5)
        return not out.stdout.strip().startswith("Z")
    except Exception:
        return True


def router_state():
    """{'pid', 'port', 'config', 'running', 'stale'} or None if never started.

    ``stale`` — the routes config on disk is newer than the running process,
    i.e. saved changes are not applied until a restart.
    """
    state = _read_state()
    if not state:
        return None
    state["running"] = _pid_alive(state.get("pid", -1))
    stale = False
    if state["running"]:
        try:
            stale = Path(state.get("config", CONFIG_PATH)).stat().st_mtime > float(
                state.get("started_at", 0))
        except Exception:
            stale = False
    state["stale"] = stale
    return state


def restart_router():
    """Stop the managed router, wait, start it on the current config.

    Returns (ok, message)."""
    state = router_state()
    if state and state.get("running"):
        ok, msg = stop_router()
        if not ok:
            return False, msg
        deadline = time.time() + 15
        while time.time() < deadline and _pid_alive(state.get("pid", -1)):
            time.sleep(0.3)
    bin_path = find_switchyard_bin()
    if not bin_path:
        return False, "switchyard executable not found — /switchyard bin <path>"
    opts = load_last_opts()
    keys = config_key_envs(CONFIG_PATH)
    ok, msg = start_router(bin_path, CONFIG_PATH, opts.get("port", DEFAULTS["port"]),
                           keys[0] if keys else "")
    return ok, ("restarted with the saved config — " + msg if ok else msg)


def _key_from_hermes_env_file(key_env):
    """Read KEY=value from $HERMES_HOME/.env (hermes's own env file).

    Agent terminal sessions run with a scrubbed environment, so the exported
    var may be invisible here even when the user has it set. The .env file is
    the sanctioned durable location; we only read it, never write it.
    """
    env_file = Path(os.environ.get("HERMES_HOME", str(Path.home() / ".hermes"))) / ".env"
    try:
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            if k.strip().removeprefix("export ").strip() == key_env:
                return v.strip().strip("\"'") or None
    except Exception:
        pass
    return None


_ENV_REF_RE_LOCAL = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


def config_key_envs(config_path):
    """All ${VAR} names referenced by the routes config."""
    try:
        return sorted(set(_ENV_REF_RE_LOCAL.findall(Path(config_path).read_text())))
    except Exception:
        return []


def start_router(bin_path, config_path, port, key_env):
    """Spawn `switchyard --routing-profiles <cfg> -- serve` detached.

    Returns (ok, message). Every key env var the config references must be set
    in this environment or present in $HERMES_HOME/.env (agent shells are
    env-scrubbed); values are passed to the router process only, never
    written anywhere.
    """
    state = router_state()
    if state and state.get("running"):
        return False, f"router already running (pid {state['pid']}, port {state['port']}) — /switchyard stop first"
    child_env = dict(os.environ)
    needed = config_key_envs(config_path) or ([key_env] if key_env else [])
    missing = []
    for var in needed:
        if child_env.get(var):
            continue
        from_file = _key_from_hermes_env_file(var)
        if from_file:
            child_env[var] = from_file
        else:
            missing.append(var)
    if missing:
        pretty = ", ".join(missing)
        return False, (f"{pretty} not set here and not in $HERMES_HOME/.env — "
                       f"add `<VAR>=<value>` lines to ~/.hermes/.env (chmod 600) or export them, then retry")
    SW_DIR.mkdir(parents=True, exist_ok=True)
    log = open(LOG_PATH, "a")
    try:
        proc = subprocess.Popen(
            [bin_path, "--routing-profiles", str(config_path), "--",
             "serve", "--host", "127.0.0.1", "--port", str(port)],
            stdout=log, stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL, start_new_session=True, env=child_env,
        )
    except Exception as exc:
        return False, f"failed to start router: {exc}"
    _write_state({"pid": proc.pid, "port": int(port), "config": str(config_path),
                  "started_at": time.time()})
    return True, (f"router starting (pid {proc.pid}) on http://127.0.0.1:{port} — "
                  f"takes ~15s to bind (upstream catalog fetch); log: {LOG_PATH}")


def stop_router():
    state = router_state()
    if not state:
        return False, "no managed router recorded (only routers started via /switchyard start are managed)"
    if not state.get("running"):
        return False, f"managed router (pid {state.get('pid')}) is not running"
    try:
        os.kill(int(state["pid"]), signal.SIGTERM)
    except Exception as exc:
        return False, f"failed to stop pid {state.get('pid')}: {exc}"
    for _ in range(20):
        if not _pid_alive(state["pid"]):
            break
        time.sleep(0.1)
    alive = _pid_alive(state["pid"])
    return (not alive), ("router stopped" if not alive else f"SIGTERM sent to pid {state['pid']} (still shutting down)")


# ---------------------------------------------------------------------------
# one-shot setup — config → key preflight → router → provider, idempotent
# ---------------------------------------------------------------------------

def setup(progress=None):
    """First-run (and re-run) setup in one call. Returns (ok, lines).

    progress, when given, is called with each line as it happens so UIs can
    stream the transcript. Existing config is kept; every step is safe to
    repeat.
    """
    import sys as _sys
    _sys.path.insert(0, str(Path(__file__).resolve().parent))
    import switchyard_client as swc

    lines = []

    def log(text):
        lines.append(text)
        if progress:
            try:
                progress(text)
            except Exception:
                pass

    bin_path = find_switchyard_bin()
    if not bin_path:
        log("✗ switchyard executable not found — install NeMo Switchyard,")
        log("  then set it once: /switchyard bin <path>  (or export SWITCHYARD_BIN)")
        return False, lines
    log(f"✓ switchyard bin: {bin_path}")

    if CONFIG_PATH.exists():
        opts = load_last_opts()
        log("✓ config exists — keeping it")
    else:
        opts = dict(DEFAULTS)
        write_config(opts)
        log("✓ wrote default config (strong=opus 4.8 · weak=nemotron ultra)")

    ok, report = preflight_report(preflight())
    for line in report.splitlines():
        log("  " + line)
    if not ok:
        log("✗ fix the failing keys above, then run setup again")
        return False, lines

    state = router_state()
    port = str((state or {}).get("port") or opts.get("port", DEFAULTS["port"]))
    if state and state.get("running"):
        log(f"✓ router already running (pid {state['pid']}, port {port})")
    else:
        keys = config_key_envs(CONFIG_PATH)
        started, msg = start_router(bin_path, CONFIG_PATH, opts.get("port", DEFAULTS["port"]),
                                    keys[0] if keys else "")
        if not started:
            log("✗ " + msg)
            return False, lines
        port = str(opts.get("port", DEFAULTS["port"]))
        log("⏳ router starting (~15s — it fetches the upstream catalog first)")
        import urllib.request as _rq
        deadline = time.time() + 75
        while time.time() < deadline:
            try:
                _rq.urlopen(f"http://127.0.0.1:{port}/health", timeout=1)
                break
            except Exception:
                time.sleep(2)
        else:
            log(f"✗ router not healthy after 75s — see {LOG_PATH}")
            return False, lines
        log(f"✓ router healthy on http://127.0.0.1:{port}")

    root = swc.detect(f"http://127.0.0.1:{port}/v1", timeout=3.0)
    if root:
        rts, _default = swc.routes(root)
        okc, msg = connect_provider(root + "/v1", [r["id"] for r in rts])
        log(("✓ " if okc else "✗ ") + msg)
    else:
        log("✗ router up but fingerprint failed — check the port")
        return False, lines

    log("✓ all set — pick the model `switchyard` (/model switchyard)")
    return True, lines


# ---------------------------------------------------------------------------
# CLI — lets agents (and humans) drive setup from the shell:
#   python3 sw_config.py init [key=value ...]
#   python3 sw_config.py start [bin=PATH] [config=PATH] [port=N]
#   python3 sw_config.py stop | status | connect [URL] | disconnect
# Mirrors the /switchyard slash commands 1:1.
# ---------------------------------------------------------------------------

def _cli(argv):
    import sys as _sys
    _sys.path.insert(0, str(Path(__file__).resolve().parent))
    cmd = argv[0] if argv else "help"
    rest = argv[1:]

    if cmd == "init":
        opts, unknown = parse_kv(" ".join(rest))
        if unknown:
            return 1, "unrecognized: " + " ".join(unknown) + "\nknown keys: " + " ".join(sorted(KNOWN_KEYS))
        path = write_config(opts)
        return 0, (f"wrote {path}\nroute: switchyard — classifier {opts['classifier']} picks between "
                   f"strong ({opts['strong']}) and weak ({opts['weak']})\n"
                   f"api key: read from ${opts['key_env']} at router start")

    if cmd == "start":
        kv = dict(tok.split("=", 1) for tok in rest if "=" in tok)
        bin_path = kv.get("bin") or find_switchyard_bin()
        if not bin_path:
            return 1, "switchyard executable not found — pass bin=PATH or export SWITCHYARD_BIN"
        cfg = Path(kv.get("config") or CONFIG_PATH)
        if not cfg.exists():
            return 1, f"no config at {cfg} — run: python3 sw_config.py init"
        key_env = DEFAULTS["key_env"]
        try:
            import re as _re
            m = _re.search(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", cfg.read_text())
            if m:
                key_env = m.group(1)
        except Exception:
            pass
        ok, msg = start_router(bin_path, cfg, kv.get("port") or DEFAULTS["port"], key_env)
        return (0 if ok else 1), msg

    if cmd == "stop":
        ok, msg = stop_router()
        return (0 if ok else 1), msg

    if cmd == "preflight":
        cfg = rest[0] if rest else None
        ok, report = preflight_report(preflight(cfg))
        return (0 if ok else 1), report

    if cmd == "setup":
        ok, lines = setup(progress=print)
        return (0 if ok else 1), ""

    if cmd == "status":
        state = router_state()
        payload = {"managed_router": state, "config": str(CONFIG_PATH),
                   "config_exists": CONFIG_PATH.exists(),
                   "switchyard_bin": find_switchyard_bin()}
        return 0, json.dumps(payload, indent=2)

    if cmd == "connect":
        import switchyard_client as swc
        url = rest[0] if rest else None
        if not url:
            state = router_state()
            if state and state.get("running"):
                url = f"http://127.0.0.1:{state['port']}/v1"
        if not url:
            return 1, "no url given and no managed router running — connect URL"
        root = swc.detect(url, timeout=2.0)
        if root is None:
            return 1, f"{url} does not fingerprint as a switchyard router (still booting? ~15s)"
        rts, _default = swc.routes(root)
        ok, msg = connect_provider(root + "/v1", [rt["id"] for rt in rts])
        return (0 if ok else 1), msg + f"\nprovider switchyard → {root}/v1 (routes: " + ", ".join(rt["id"] for rt in rts) + ")"

    if cmd == "disconnect":
        ok, msg = disconnect_provider()
        return (0 if ok else 1), msg

    return 1, ("usage: sw_config.py init [k=v ...] | start [bin= config= port=] | stop | "
               "status | connect [URL] | disconnect")


if __name__ == "__main__":
    import sys as _sys
    _code, _msg = _cli(_sys.argv[1:])
    print(_msg)
    _sys.exit(_code)
